### ISSUE TITLE
Errorcode verschilt, maar inhoud is hetzeflde

### ISSUE THREAD

**Issue by hyhyn** [DennisHakvoort/leany-mcleanface#82]
https://github.com/DennisHakvoort/leany-mcleanface/blob/af405f08056bbcd03309fcfae43b9b24dccb7e7c/Tests.sql#L627
50004, 'Een project kan niet meer aangepast worden nadat deze is afgelopen.'
50001, 'Een project kan niet meer aangepast worden nadat deze is afgelopen.'
staat atm in de triggers (BR9)

**Comment by MugiwaraSama** [comment]
is nu veranderd, zie tests branch
